// <auto-generated />
namespace DocumentManage.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class V001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V001));
        
        string IMigrationMetadata.Id
        {
            get { return "201711250326453_V0.0.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
